const questions = [
  {
    id: 1,
    title: "How do I center an element using CSS?",
    body: "<p>I want to center an element in the middle of its container. What is the best way to do this with CSS?</p>",
    skills: [{ value: "css", label: "CSS" }],
    votes: [{ id: [], up: 3, down: 0 }],
  },
  {
    id: 2,
    title: "What is the difference between let, const, and var in JavaScript?",
    body: "<p>I am new to JavaScript and I am not sure when to use let, const, or var when declaring variables. Can someone explain the differences between these keywords?</p>",
    skills: [{ value: "javascript", label: "JavaScript" }],
    votes: [{ id: [], up: 5, down: 1 }],
  },
  {
    id: 3,
    title: "How do I use async/await in JavaScript?",
    body: "<p>I have heard that async/await is a useful feature in JavaScript, but I am not sure how to use it. Can someone provide an example of async/await in action?</p>",
    skills: [{ value: "javascript", label: "JavaScript" }],
    votes: [{ id: [], up: 2, down: 0 }],
  },
  {
    id: 4,
    title: "How do I make a POST request using Node.js?",
    body: "<p>I need to make a POST request to a server using Node.js. What is the best way to do this?</p>",
    skills: [{ value: "nodejs", label: "Node.js" }],
    votes: [{ id: [], up: 1, down: 0 }],
  },
  {
    id: 5,
    title: "What is the box model in CSS?",
    body: "<p>I have heard that understanding the box model is important for working with CSS, but I am not sure what it is. Can someone explain the box model?</p>",
    skills: [{ value: "css", label: "CSS" }],
    votes: [{ id: [], up: 4, down: 1 }],
  },
  {
    id: 6,
    title: "How do I use map() in JavaScript?",
    body: "<p>I have an array of items and I need to transform each item using a function. I have heard that map() is a useful function for this in JavaScript. How do I use map()?</p>",
    skills: [{ value: "javascript", label: "JavaScript" }],
    votes: [{ id: [], up: 2, down: 0 }],
  },
  {
    id: 7,
    title: "How do I add event listeners in JavaScript?",
    body: "<p>I want to add a click event listener to a button using JavaScript. What is the best way to do this?</p>",
    skills: [{ value: "javascript", label: "JavaScript" }],
    votes: [{ id: [], up: 3, down: 0 }],
  },
  {
    id: 8,
    title: "How do I use flexbox in CSS?",
    body: "<p>I want to use flexbox to create a responsive layout for my website, but I am not sure how to get started. Can someone explain the basics of flexbox?</p>",
    skills: [{ value: "css", label: "CSS" }],
    votes: [{ id: [], up: 2, down: 0 }],
  },
  {
    id: 9,
    title: "How do I use React Router?",
    body: "<p>I want to use flexbox to create a responsive layout for my website, but I am not sure how to get started. Can someone explain the basics of flexbox?</p>",
    skills: [{ value: "css", label: "CSS" }],
    votes: [{ id: [], up: 2, down: 0 }],
  },
  {
    id: 10,
    title: "What is the difference between null and undefined in JavaScript?",
    body: "<p>I am not sure what the difference between null and undefined is in JavaScript. Can someone explain?</p>",
    skills: [{ value: "javascript", label: "JavaScript" }],
    votes: [{ id: [], up: 4, down: 0 }],
  },
  {
    id: 11,
    title: "How do I create a basic HTML form?",
    body: "<p>I want to create a simple form with a few input fields and a submit button. What is the basic structure of an HTML form?</p>",
    skills: [{ value: "html", label: "HTML" }],
    votes: [{ id: [], up: 1, down: 0 }],
  },
  {
    id: 12,
    title: "How do I use Bootstrap?",
    body: "<p>I have heard that Bootstrap is a useful framework for building responsive websites, but I am not sure how to get started. Can someone provide an introduction to Bootstrap?</p>",
    skills: [{ value: "css", label: "CSS" }],
    votes: [{ id: [], up: 3, down: 0 }],
  },
  {
    id: 13,
    title: "How do I add a class to an element using JavaScript?",
    body: "<p>I want to add a class to an element on my web page using JavaScript. What is the best way to do this?</p>",
    skills: [{ value: "javascript", label: "JavaScript" }],
    votes: [{ id: [], up: 2, down: 0 }],
  },
  {
    id: 14,
    title: "How do I use the spread operator in JavaScript?",
    body: "<p>I have heard that the spread operator is a useful feature in JavaScript, but I am not sure how to use it. Can someone provide an example of the spread operator in action?</p>",
    skills: [{ value: "javascript", label: "JavaScript" }],
    votes: [{ id: [], up: 3, down: 0 }],
  },
  {
    id: 15,
    title: "What is Node.js?",
    body: "<p>I am new to web development and have heard a lot about Node.js. Can someone explain what it is and why it is useful?</p>",
    skills: [{ value: "nodejs", label: "Node.js" }],
    votes: [{ id: [], up: 5, down: 0 }],
  },
  {
    id: 16,
    title: "How do I use CSS Grid?",
    body: "<p>I want to create a complex grid layout on my web page using CSS Grid. What is the best way to get started with CSS Grid?</p>",
    skills: [{ value: "css", label: "CSS" }],
    votes: [{ id: [], up: 2, down: 0 }],
  },
  {
    id: 17,
    title: "What is the difference between HTTP and HTTPS?",
    body: "<p>I am not sure what the difference between HTTP and HTTPS is. Can someone explain the differences?</p>",
    skills: [{ value: "html", label: "HTML" }],
    votes: [{ id: [], up: 4, down: 0 }],
  },
  {
    id: 18,
    title: "How do I use promises in JavaScript?",
    body: "<p>I have heard that promises are a useful feature in JavaScript, but I am not sure how to use them. Can someone provide an example of promises in action?</p>",
    skills: [{ value: "javascript", label: "JavaScript" }],
    votes: [{ id: [], up: 5, down: 1 }],
  }
];

export default questions;
